version: '3.1'

services:

  app:
    container_name: api
    restart: always
    build: .
    ports:
      - ${PORT_HTTP}:${PORT_HTTP}
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
    - certificate:/certificate
    - configuration:/configuration

  db:
    container_name: postgres
    restart: always
    build: ./database
    ports:
      - '5444:${DB_PORT}'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  adminer:
    image: adminer:4.8.1-standalone
    restart: unless-stopped
    ports:
      - 8080:8080

volumes: 
  data: {}
  certificate: {}
  configuration: {}


